### PR TITLE
update instructions for macOS

### PR DESCRIPTION
**Pull request by retokromer**

### CODE REVIEW

**Comment by retokromer** [comment]
ping

**Comment by retokromer** [comment]
ping ping

**Comment by retokromer** [comment]
What is the problem with this PR? The installation on macOS via
```
brew install rawtoaces
```
works very well since longtime.

**Comment by agentirons** [comment]
The pull requests on this project tend to take a very long time to resolve, I don't think it's watched very closely. @miaoqi? @scottdyer?

**Comment by scottdyer** [comment]
Hey @agentirons @retokromer, 
@miaoqi no longer works for us and this project currently has no official maintainer. There is, however, a plan underway to resurrect it and give it long-term support. Thanks for your input and stay tuned.

**Comment by retokromer** [comment]
@scottdyer Thank you for the information!

**Pull request merged**
